server:
  port: ${API_GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost"
              - "http://ijp.example.com"
              - "https://ijp.example.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: login-service
          uri: ${LOGIN_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/auth/**
        - id: hr-service
          uri: ${HR_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/api/hr/**
        - id: job-service
          uri: ${JOB_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/api/jobs/**
        - id: candidate-service
          uri: ${CANDIDATE_SERVICE_URI:http://localhost:8084}
          predicates:
            - Path=/api/candidates/**
        - id: employee-service
          uri: ${EMPLOYEE_SERVICE_URI:http://localhost:8085}
          predicates:
            - Path=/api/employees/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
