server:
  port: ${CANDIDATE_SERVICE_PORT:8084}

spring:
  application:
    name: candidate-service
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
