server:
  port: ${EMPLOYEE_SERVICE_PORT:8085}

spring:
  application:
    name: employee-service
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
