server:
  port: ${JOB_SERVICE_PORT:8083}

spring:
  application:
    name: job-service
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    discovery:
      client:
        simple:
          instances:
            candidate-service:
              - uri: ${CANDIDATE_SERVICE_URI:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: "*"
