server:
  port: ${LOGIN_SERVICE_PORT:8081}

spring:
  application:
    name: login-service
  cloud:
    discovery:
      client:
        simple:
          instances:
            hr-service:
              - uri: ${HR_SERVICE_URI:http://localhost:8082}
            employee-service:
              - uri: ${EMPLOYEE_SERVICE_URI:http://localhost:8085}

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  expiration: ${JWT_EXPIRATION:86400000}
